import { Injectable } from '@angular/core';
import { Project } from '../models/project.model';

@Injectable({
  providedIn: 'root',
})
export class ProjectService {
  private projects: Project[] = [
    {
      id: 1,
      title: 'Seatd Project',
      description:
        'Development of a tool to monitor office occupancy and enable workplace reservations',
      image: '/images/clients/elision.png',
      tags: [
        'Spring Boot 2',
        'Java 11',
        'Angular 11',
        'Azure Cloud',
        'AWS',
        'E2E Testing',
        'DDD',
        'Mockito',
        'Firebase',
        'Docker',
        'Kubernetes',
        'Maven',
      ],
      client: 'Elision',
      startDate: new Date('2020-09-01'),
      endDate: new Date('2021-02-28'),
    },
    {
      id: 2,
      title: 'ACA Group Website',
      description: 'New website based on popular JAMstack tools',
      image: '/images/clients/aca-group.png',
      tags: ['GatsbyJS', 'React', 'JavaScript', 'CSS/SCSS', 'Netlify', 'NPM', 'Gulp'],
      client: 'ACA Group',
      startDate: new Date('2021-09-01'),
      endDate: new Date('2024-02-29'),
    },
    {
      id: 3,
      title: 'JAMstack Research & Development',
      description:
        'Research and comparison of JAMstack tools and development of a recruitment application',
      image: '/images/clients/aca-group.png',
      tags: ['GatsbyJS', 'React', 'Angular', 'JavaScript', 'CSS/SCSS', 'Netlify', 'NPM', 'Gulp'],
      client: 'ACA Group',
      startDate: new Date('2021-03-01'),
      endDate: new Date('2021-06-30'),
    },
    {
      id: 4,
      title: 'Springer Nature Theme Migration',
      description: 'Migration of an old Liferay theme to a newer version',
      image: '/images/clients/springer-nature.jpeg',
      tags: [
        'Java',
        'CSS/SCSS',
        'JavaScript',
        'OSGI modules',
        'Jenkins',
        'Docker',
        'Kubernetes',
        'Maven',
        'NPM',
      ],
      client: 'Springer Nature',
      startDate: new Date('2021-11-01'),
      endDate: new Date('2022-01-31'),
    },
    {
      id: 5,
      title: 'IntraBlox SAAS Solution',
      description: 'In-house SAAS solution to offer Liferay to smaller companies',
      image: '/images/clients/aca-group.png',
      tags: [
        'Freemarker',
        'Groovy',
        'Java',
        'REST',
        'AWS',
        'JUnit',
        'DDD',
        'OSGI modules',
        'Jenkins',
        'Docker',
        'Kubernetes',
        'Maven',
      ],
      client: 'ACA Group',
      startDate: new Date('2021-09-01'),
      endDate: new Date('2024-02-29'),
    },
    {
      id: 6,
      title: 'De Watergroep Portal',
      description:
        'Liferay portal for administration and document management for employees and customers of De Watergroep',
      image: '/images/clients/dwg.svg',
      tags: [
        'Spring Boot 3',
        'Java',
        'Angular 14+',
        'Reactive Programming',
        'Project Reactor',
        'Azure Cloud',
        'AWS',
        'E2E Testing',
        'Wiremock',
        'DDD',
        'OSGI modules',
        'Jenkins',
        'Docker',
        'Kubernetes',
        'Maven',
      ],
      client: 'De Watergroep',
      startDate: new Date('2022-03-01'),
      endDate: new Date('2024-02-29'),
    },
    {
      id: 7,
      title: 'Intern Training',
      description: 'Training and supporting an intern within our team',
      image: '/images/clients/aca-group.png',
      tags: ['Mentoring', 'Training', 'Leadership'],
      client: 'ACA Group',
      startDate: new Date('2022-03-01'),
      endDate: new Date('2022-06-30'),
    },
    {
      id: 8,
      title: 'Tennis en Padel Vlaanderen Migration',
      description:
        'Migration of old website and administration to new Liferay portal, responsible for codebase migration and supporting the internal team',
      image: '/images/clients/tennis-padel-vlaanderen.png',
      tags: [
        'JSP',
        'Java',
        'AWS',
        'JUnit',
        'DDD',
        'OSGI modules',
        'Jenkins',
        'Docker',
        'Kubernetes',
        'Maven',
      ],
      client: 'Tennis en Padel Vlaanderen',
      startDate: new Date('2022-11-01'),
      endDate: new Date('2024-02-29'),
    },
    {
      id: 9,
      title: 'Jessa Hospital Platform',
      description: 'New website(s) and internal platform for employees in new Liferay portal',
      image: '/images/clients/jessa-ziekenhuis.jpg',
      tags: [
        'Spring Boot 3',
        'Freemarker',
        'Groovy',
        'Java',
        'SOAP',
        'REST',
        'Azure Cloud',
        'AWS',
        'JUnit',
        'DDD',
        'OSGI modules',
        'Jenkins',
        'Docker',
        'Kubernetes',
        'Maven',
        'Gradle',
      ],
      client: 'Jessa Ziekenhuis',
      startDate: new Date('2021-09-01'),
      endDate: new Date('2024-02-29'),
    },
    {
      id: 10,
      title: 'Graco IT Support',
      description:
        'Support for internal IT department with issues related to UI/Tomcat servers and general Java questions',
      image: '/images/clients/graco.jpeg',
      tags: [
        'Freemarker',
        'Groovy',
        'Java',
        'SOAP',
        'REST',
        'JUnit',
        'OSGI modules',
        'Jenkins',
        'Docker',
        'Kubernetes',
        'Maven',
        'Gradle',
        'Tomcat',
      ],
      client: 'Graco',
      startDate: new Date('2023-06-01'),
      endDate: new Date('2023-06-30'),
    },
    {
      id: 11,
      title: 'Mynexuzhealth Patient Portal',
      description:
        'Full-stack development for Mynexuzhealth solutions, focusing on digital patient record access (web/mobile)',
      image: '/images/clients/nexuzhealth.jpeg',
      tags: [
        'Java',
        'Angular 17/18',
        'Nx Console',
        'Golang',
        'gRPC',
        'AWS',
        'Google Cloud Platform',
        'Microservices',
        'Docker',
        'Kubernetes',
        'Maven',
        'Figma',
      ],
      client: 'Nexuzhealth',
      startDate: new Date('2024-03-01'),
      endDate: new Date('2024-12-31'),
    },
    {
      id: 12,
      title: 'Starttoets & Columbus Platform',
      description:
        'Full-stack development on digital assessment and registration platforms for the Flemish education system, with a strong focus on performance, scalability, and maintainability.',
      image: '/images/clients/vlaamse-overheid.png',
      tags: [
        'Spring Boot 3',
        'Java 17',
        'Angular 16+',
        'RxJS',
        'PostgreSQL',
        'REST APIs',
        'CI/CD',
        'DDD',
        'Jenkins',
        'Docker',
        'AWS',
        'Jest',
      ],
      client: 'Vlaamse Overheid (Onderwijs & Vorming)',
      startDate: new Date('2025-01-01'),
    },
  ];

  getProjects(): Project[] {
    return this.projects;
  }
}
